version: '3'
services:
### Mysql container
  mysql:
    #build: ./bin/mysql
    container_name: 'png-mysql'
    restart: 'always'
    #image name:tag
    image: mysql:latest
    ports:
      # "localport:dockerport"
      - "33061:3306" 
      - "33062:33060"
    volumes:
      # "localport:dockerport"
      - /var/www/docker-compose-lamp/bin/mysql/db:/docker-entrypoint-initdb.d
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test_pass